version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_CREATE_TOPICS: "your_topic_name:1:1"
    volumes:
      - ./kafka-data:/var/lib/kafka/data

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"

  # Add other components as needed, such as Kafka Connect, REST Proxy, etc.

  producer:
    build:
      context: ./producer
    container_name: producer
    volumes:
      - ./producer:/app  # Mount the producer directory into the container
    depends_on:
      - kafka  # Ensure the Kafka service is started first

  consumer:
    build:
      context: ./consumer
    container_name: consumer
    volumes:
      - ./consumer:/app  # Mount the consumer directory into the container
    depends_on:
      - kafka  # Ensure the Kafka service is started first
